### ISSUE TITLE
着信音つける

### ISSUE THREAD

**Issue by Haruk1y** [Haruk1y/Socket_C#1]

**Comment by taiseiii345** [comment]
繋がったらpopenでplayすればよい?

**Comment by Haruk1y** [comment]
①サーバー側：開いておく
②クライアント側：サーバー側に接続試行．自分の情報を送信
③サーバー側：音を鳴らす．入力の情報を表示してとるかとらないか入力
④OKしたら音声入力を受け取り始める

**Comment by taiseiii345** [comment]
着信音がなっている間に取るか取らないかを決められるということか!

**Comment by Haruk1y** [comment]
着信音なってる間は入力をバッファかどっかに垂れ流し

**Comment by Haruk1y** [comment]
連絡先.txt
Name1, IP1
Name2, IP2
...
みたいな感じで保存しといて，実行時にNameを引数として与えることでIPに変換してくれる
